### PR TITLE
Add server option to onion and remove protocol and transform

### PR DESCRIPTION
**Pull request by arj03**

### CODE REVIEW

**Comment by dominictarr** [comment]
cool, looks good

**Comment by dominictarr** [comment]
merged into 1.7.0

**Comment by dominictarr** [comment]
ah, this isn't quite enough...
i got this error
```
Error: could not parse address:net:localhost:25139~shs:bob3PzV+FJy8Xs6TtRBbWPhnOi53Brp7A+AG66XsJCY=;onion:localhost:~shs:bob3PzV+FJy8Xs6TtRBbWPhnOi53Brp7A+AG66XsJCY=
    at Object.client (/home/dominic/c/secret-stack/node_modules/multiserver/compose.js:53:27)
    at Object.client (/home/dominic/c/secret-stack/node_modules/multiserver/index.js:24:21)
    at EventEmitter.connect (/home/dominic/c/secret-stack/index.js:182:14)
    at EventEmitter.hooked [as connect] (/home/dominic/c/secret-stack/node_modules/hoox/index.js:10:15)
    at Test.<anonymous> (/home/dominic/c/secret-stack/test/app-key.js:67:9)
    at Test.bound [as _cb] (/home/dominic/c/secret-stack/node_modules/tape/lib/test.js:63:32)
    at Test.run (/home/dominic/c/secret-stack/node_modules/tape/lib/test.js:82:10)
    at Test.bound [as run] (/home/dominic/c/secret-stack/node_modules/tape/lib/test.js:63:32)
    at Immediate.next (/home/dominic/c/secret-stack/node_modules/tape/lib/results.js:70:15)
```

when I tried to run secret-stack tests using this version of multiserver.
I think it shouldn't make an address with onion in it doesn't have an onion server...

**Comment by dominictarr** [comment]
this currently returns "onion:localhost:" as an address, but that doesn't make any sense as an onion address.

**Comment by dominictarr** [comment]
okay, fixed this stuff in 1.7.1 and now secret-stack tests pass

**Comment by dominictarr** [comment]
okay, I think this should work, but am getting negioation error (5),
but I think that is progress actually. I'll try again when I have a better connection.

**Comment by arj03** [comment]
Yeah my pub is back to continious crashing again :(

**Pull request merged**
